### ISSUE TITLE
tmux crashes when exiting htop buoy

### ISSUE THREAD

**Issue by jby** [navahas/tmux-buoyshell#3]
As per https://www.reddit.com/r/tmux/comments/1jrec4b/comment/mltvqlg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Tried to add screen recording here, but it failed.

**Comment by navahas** [comment]
Thanks for the follow-up! I have the same macOS and tmux version. Then I tried, without success, switching my default shell to zsh and even ran iTerm2 directly as the shell, just in case it was somehow related.

Does that happen with other commands? Can you try another command that runs a process you need to exit, like man man?

Another possibility is to have some conflicting settings in your tmux.conf.

Hopefully the GH issue gets sorted so you can drop that screen recording in. Might help narrow things down!

**Comment by jby** [comment]
I thought it was related to the fact I was trying to upload it from work, and that our firewalls wouldn't allow me.
But now I've just tried from home, on a different computer, but I'm still unable to upload the screen recording... :(

**Comment by jby** [comment]
I managed to upload it to YouTube: https://youtube.com/shorts/TgB-SM0bbbQ?feature=share

**Comment by jby** [comment]
I've done some more testing and it's the `htop` buoy specifically.
Start it, let it refresh, quit htop, Ctrl-D quit the buoy => tmux crash
If I start another for instance prefix Q and run htop in that, quit it and Ctrl-D out of the Buoy it doesn't crash.
Could it be related to the `ephemeral` setting?
I just tried manually with prefix `: run-shell "custom_buoy ephemeral test"` it starts an empty shell, and if I exit that it takes tmux with it...

**Comment by jby** [comment]
My current tmux.conf: https://gist.github.com/jby/1de177f49e028757a31eee08ac979134

**Comment by navahas** [comment]
I feel was related to a typo! Just pushed the fix. Let me know once you try again with the latest repo version.

Hopefully this solves the issue, otherwise will keep testing with your tmux.conf further.

**Comment by jby** [comment]
Yes, now it doesn't crash anymore, the tmux session survives, but I do get an error message when exiting the ephemeral buoy:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/1cf6a599-1145-4d0d-b599-5754b4710c03" />

**Comment by navahas** [comment]
That should be fixed by now. I think, finally, there should be no further errors. Keep me posted! @jby

**Comment by jby** [comment]
Maybe it _shouldn't_, but there is - not the same, but still an error message...

<img width="1712" alt="Image" src="https://github.com/user-attachments/assets/0ab7b25f-e532-4688-8569-5ad0b69cd33e" />

**Comment by navahas** [comment]
Ah, it came down to speed! I use Fish and a minimal setup, so I couldn’t reproduce the behavior with the same code. I’ve gone back to my original pre-refactor logic using a tmux hook to cleanly kill the session. Thanks for your patience, and for helping sort this out!

**Comment by jby** [comment]
I'll test it tomorrow (it's 11pm here now) and report back.

**Comment by jby** [comment]
Yes, I'd say it's fixed now - thank you!
